/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.orchestration.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kb.orchestration.model.RetrieveInterestResponseInterest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Output: ReBQ Retrieve details of an interest transaction applied internally to the account
 */
@Schema(description = "Output: ReBQ Retrieve details of an interest transaction applied internally to the account")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class RetrieveInterestResponse {
  @JsonProperty("Interest")
  private RetrieveInterestResponseInterest interest = null;

  public RetrieveInterestResponse interest(RetrieveInterestResponseInterest interest) {
    this.interest = interest;
    return this;
  }

   /**
   * Get interest
   * @return interest
  **/
  @Schema(description = "")
  public RetrieveInterestResponseInterest getInterest() {
    return interest;
  }

  public void setInterest(RetrieveInterestResponseInterest interest) {
    this.interest = interest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveInterestResponse retrieveInterestResponse = (RetrieveInterestResponse) o;
    return Objects.equals(this.interest, retrieveInterestResponse.interest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveInterestResponse {\n");
    
    sb.append("    interest: ").append(toIndentedString(interest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
