/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.orchestration.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * ServiceFees
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class ServiceFees {
  @JsonProperty("FeeConfigurationProfile")
  private String feeConfigurationProfile = null;

  @JsonProperty("FeeType")
  private String feeType = null;

  @JsonProperty("FeeDefinition")
  private String feeDefinition = null;

  @JsonProperty("FeeApplicationRecord")
  private String feeApplicationRecord = null;

  @JsonProperty("FeeTransaction")
  private String feeTransaction = null;

  @JsonProperty("TransactionDescription")
  private String transactionDescription = null;

  @JsonProperty("TransactionFeeType")
  private String transactionFeeType = null;

  @JsonProperty("TransactionFeeCharge")
  private String transactionFeeCharge = null;

  @JsonProperty("FeeProjectionsandCommitments")
  private String feeProjectionsandCommitments = null;

  @JsonProperty("ProjectedTransactionDescription")
  private String projectedTransactionDescription = null;

  @JsonProperty("ProjectedTransactionFeeType")
  private String projectedTransactionFeeType = null;

  @JsonProperty("ProjectedTransactionFeeCharge")
  private String projectedTransactionFeeCharge = null;

  @JsonProperty("FeeAccrualAmount")
  private Amount feeAccrualAmount = null;

  @JsonProperty("AccrualFeeType")
  private String accrualFeeType = null;

  @JsonProperty("AccrualFeeCharge")
  private String accrualFeeCharge = null;

  public ServiceFees feeConfigurationProfile(String feeConfigurationProfile) {
    this.feeConfigurationProfile = feeConfigurationProfile;
    return this;
  }

   /**
   * The profile of applicable fees and penalties
   * @return feeConfigurationProfile
  **/
  @Schema(description = "The profile of applicable fees and penalties")
  public String getFeeConfigurationProfile() {
    return feeConfigurationProfile;
  }

  public void setFeeConfigurationProfile(String feeConfigurationProfile) {
    this.feeConfigurationProfile = feeConfigurationProfile;
  }

  public ServiceFees feeType(String feeType) {
    this.feeType = feeType;
    return this;
  }

   /**
   * The fee or penalty type applied
   * @return feeType
  **/
  @Schema(description = "The fee or penalty type applied")
  public String getFeeType() {
    return feeType;
  }

  public void setFeeType(String feeType) {
    this.feeType = feeType;
  }

  public ServiceFees feeDefinition(String feeDefinition) {
    this.feeDefinition = feeDefinition;
    return this;
  }

   /**
   * Definition of the fee or penalty including when and how to apply
   * @return feeDefinition
  **/
  @Schema(description = "Definition of the fee or penalty including when and how to apply")
  public String getFeeDefinition() {
    return feeDefinition;
  }

  public void setFeeDefinition(String feeDefinition) {
    this.feeDefinition = feeDefinition;
  }

  public ServiceFees feeApplicationRecord(String feeApplicationRecord) {
    this.feeApplicationRecord = feeApplicationRecord;
    return this;
  }

   /**
   * The record of applied fees and penalties including transactions and accrued amounts
   * @return feeApplicationRecord
  **/
  @Schema(description = "The record of applied fees and penalties including transactions and accrued amounts")
  public String getFeeApplicationRecord() {
    return feeApplicationRecord;
  }

  public void setFeeApplicationRecord(String feeApplicationRecord) {
    this.feeApplicationRecord = feeApplicationRecord;
  }

  public ServiceFees feeTransaction(String feeTransaction) {
    this.feeTransaction = feeTransaction;
    return this;
  }

   /**
   * A record of an applied fee or penalty
   * @return feeTransaction
  **/
  @Schema(description = "A record of an applied fee or penalty")
  public String getFeeTransaction() {
    return feeTransaction;
  }

  public void setFeeTransaction(String feeTransaction) {
    this.feeTransaction = feeTransaction;
  }

  public ServiceFees transactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
    return this;
  }

   /**
   * General description of the fee or penalty transaction
   * @return transactionDescription
  **/
  @Schema(description = "General description of the fee or penalty transaction")
  public String getTransactionDescription() {
    return transactionDescription;
  }

  public void setTransactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
  }

  public ServiceFees transactionFeeType(String transactionFeeType) {
    this.transactionFeeType = transactionFeeType;
    return this;
  }

   /**
   * The fee or penalty type applied
   * @return transactionFeeType
  **/
  @Schema(description = "The fee or penalty type applied")
  public String getTransactionFeeType() {
    return transactionFeeType;
  }

  public void setTransactionFeeType(String transactionFeeType) {
    this.transactionFeeType = transactionFeeType;
  }

  public ServiceFees transactionFeeCharge(String transactionFeeCharge) {
    this.transactionFeeCharge = transactionFeeCharge;
    return this;
  }

   /**
   * The derived fee or penalty amount applied
   * @return transactionFeeCharge
  **/
  @Schema(description = "The derived fee or penalty amount applied")
  public String getTransactionFeeCharge() {
    return transactionFeeCharge;
  }

  public void setTransactionFeeCharge(String transactionFeeCharge) {
    this.transactionFeeCharge = transactionFeeCharge;
  }

  public ServiceFees feeProjectionsandCommitments(String feeProjectionsandCommitments) {
    this.feeProjectionsandCommitments = feeProjectionsandCommitments;
    return this;
  }

   /**
   * A record of projected fees and penalties
   * @return feeProjectionsandCommitments
  **/
  @Schema(description = "A record of projected fees and penalties")
  public String getFeeProjectionsandCommitments() {
    return feeProjectionsandCommitments;
  }

  public void setFeeProjectionsandCommitments(String feeProjectionsandCommitments) {
    this.feeProjectionsandCommitments = feeProjectionsandCommitments;
  }

  public ServiceFees projectedTransactionDescription(String projectedTransactionDescription) {
    this.projectedTransactionDescription = projectedTransactionDescription;
    return this;
  }

   /**
   * General description of the projected fee or penalty
   * @return projectedTransactionDescription
  **/
  @Schema(description = "General description of the projected fee or penalty")
  public String getProjectedTransactionDescription() {
    return projectedTransactionDescription;
  }

  public void setProjectedTransactionDescription(String projectedTransactionDescription) {
    this.projectedTransactionDescription = projectedTransactionDescription;
  }

  public ServiceFees projectedTransactionFeeType(String projectedTransactionFeeType) {
    this.projectedTransactionFeeType = projectedTransactionFeeType;
    return this;
  }

   /**
   * The fee or penalty type
   * @return projectedTransactionFeeType
  **/
  @Schema(description = "The fee or penalty type")
  public String getProjectedTransactionFeeType() {
    return projectedTransactionFeeType;
  }

  public void setProjectedTransactionFeeType(String projectedTransactionFeeType) {
    this.projectedTransactionFeeType = projectedTransactionFeeType;
  }

  public ServiceFees projectedTransactionFeeCharge(String projectedTransactionFeeCharge) {
    this.projectedTransactionFeeCharge = projectedTransactionFeeCharge;
    return this;
  }

   /**
   * The anticipated fee or penalty amount
   * @return projectedTransactionFeeCharge
  **/
  @Schema(description = "The anticipated fee or penalty amount")
  public String getProjectedTransactionFeeCharge() {
    return projectedTransactionFeeCharge;
  }

  public void setProjectedTransactionFeeCharge(String projectedTransactionFeeCharge) {
    this.projectedTransactionFeeCharge = projectedTransactionFeeCharge;
  }

  public ServiceFees feeAccrualAmount(Amount feeAccrualAmount) {
    this.feeAccrualAmount = feeAccrualAmount;
    return this;
  }

   /**
   * Get feeAccrualAmount
   * @return feeAccrualAmount
  **/
  @Schema(description = "")
  public Amount getFeeAccrualAmount() {
    return feeAccrualAmount;
  }

  public void setFeeAccrualAmount(Amount feeAccrualAmount) {
    this.feeAccrualAmount = feeAccrualAmount;
  }

  public ServiceFees accrualFeeType(String accrualFeeType) {
    this.accrualFeeType = accrualFeeType;
    return this;
  }

   /**
   * The fee or penalty type being tracked
   * @return accrualFeeType
  **/
  @Schema(description = "The fee or penalty type being tracked")
  public String getAccrualFeeType() {
    return accrualFeeType;
  }

  public void setAccrualFeeType(String accrualFeeType) {
    this.accrualFeeType = accrualFeeType;
  }

  public ServiceFees accrualFeeCharge(String accrualFeeCharge) {
    this.accrualFeeCharge = accrualFeeCharge;
    return this;
  }

   /**
   * The accrued amount of fees and penalties
   * @return accrualFeeCharge
  **/
  @Schema(description = "The accrued amount of fees and penalties")
  public String getAccrualFeeCharge() {
    return accrualFeeCharge;
  }

  public void setAccrualFeeCharge(String accrualFeeCharge) {
    this.accrualFeeCharge = accrualFeeCharge;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceFees serviceFees = (ServiceFees) o;
    return Objects.equals(this.feeConfigurationProfile, serviceFees.feeConfigurationProfile) &&
        Objects.equals(this.feeType, serviceFees.feeType) &&
        Objects.equals(this.feeDefinition, serviceFees.feeDefinition) &&
        Objects.equals(this.feeApplicationRecord, serviceFees.feeApplicationRecord) &&
        Objects.equals(this.feeTransaction, serviceFees.feeTransaction) &&
        Objects.equals(this.transactionDescription, serviceFees.transactionDescription) &&
        Objects.equals(this.transactionFeeType, serviceFees.transactionFeeType) &&
        Objects.equals(this.transactionFeeCharge, serviceFees.transactionFeeCharge) &&
        Objects.equals(this.feeProjectionsandCommitments, serviceFees.feeProjectionsandCommitments) &&
        Objects.equals(this.projectedTransactionDescription, serviceFees.projectedTransactionDescription) &&
        Objects.equals(this.projectedTransactionFeeType, serviceFees.projectedTransactionFeeType) &&
        Objects.equals(this.projectedTransactionFeeCharge, serviceFees.projectedTransactionFeeCharge) &&
        Objects.equals(this.feeAccrualAmount, serviceFees.feeAccrualAmount) &&
        Objects.equals(this.accrualFeeType, serviceFees.accrualFeeType) &&
        Objects.equals(this.accrualFeeCharge, serviceFees.accrualFeeCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeConfigurationProfile, feeType, feeDefinition, feeApplicationRecord, feeTransaction, transactionDescription, transactionFeeType, transactionFeeCharge, feeProjectionsandCommitments, projectedTransactionDescription, projectedTransactionFeeType, projectedTransactionFeeCharge, feeAccrualAmount, accrualFeeType, accrualFeeCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceFees {\n");
    
    sb.append("    feeConfigurationProfile: ").append(toIndentedString(feeConfigurationProfile)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("    feeDefinition: ").append(toIndentedString(feeDefinition)).append("\n");
    sb.append("    feeApplicationRecord: ").append(toIndentedString(feeApplicationRecord)).append("\n");
    sb.append("    feeTransaction: ").append(toIndentedString(feeTransaction)).append("\n");
    sb.append("    transactionDescription: ").append(toIndentedString(transactionDescription)).append("\n");
    sb.append("    transactionFeeType: ").append(toIndentedString(transactionFeeType)).append("\n");
    sb.append("    transactionFeeCharge: ").append(toIndentedString(transactionFeeCharge)).append("\n");
    sb.append("    feeProjectionsandCommitments: ").append(toIndentedString(feeProjectionsandCommitments)).append("\n");
    sb.append("    projectedTransactionDescription: ").append(toIndentedString(projectedTransactionDescription)).append("\n");
    sb.append("    projectedTransactionFeeType: ").append(toIndentedString(projectedTransactionFeeType)).append("\n");
    sb.append("    projectedTransactionFeeCharge: ").append(toIndentedString(projectedTransactionFeeCharge)).append("\n");
    sb.append("    feeAccrualAmount: ").append(toIndentedString(feeAccrualAmount)).append("\n");
    sb.append("    accrualFeeType: ").append(toIndentedString(accrualFeeType)).append("\n");
    sb.append("    accrualFeeCharge: ").append(toIndentedString(accrualFeeCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
