/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.orchestration.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.kb.orchestration.model.Currencycode;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * UpdateSavingsAccountFacilityRequestSavingsAccountFacility
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class UpdateSavingsAccountFacilityRequestSavingsAccountFacility {
  @JsonProperty("ProductInstanceReference")
  private String productInstanceReference = null;

  @JsonProperty("SavingsAccountNumber")
  private String savingsAccountNumber = null;

  @JsonProperty("CustomerReference")
  private String customerReference = null;

  @JsonProperty("BankBranchLocationReference")
  private String bankBranchLocationReference = null;

  @JsonProperty("AccountType")
  private String accountType = null;

  @JsonProperty("AccountCurrency")
  private Currencycode accountCurrency = null;

  @JsonProperty("TaxReference")
  private String taxReference = null;

  @JsonProperty("EntitlementOptionDefinition")
  private String entitlementOptionDefinition = null;

  @JsonProperty("EntitlementOptionSetting")
  private String entitlementOptionSetting = null;

  @JsonProperty("RestrictionOptionDefinition")
  private String restrictionOptionDefinition = null;

  @JsonProperty("RestrictionOptionSetting")
  private String restrictionOptionSetting = null;

  @JsonProperty("Associations")
  private String associations = null;

  @JsonProperty("AssociationType")
  private String associationType = null;

  @JsonProperty("AssociationObligationEntitlement")
  private String associationObligationEntitlement = null;

  @JsonProperty("AssociationReference")
  private String associationReference = null;

  @JsonProperty("LinkedAccounts")
  private String linkedAccounts = null;

  @JsonProperty("LinkType")
  private String linkType = null;

  @JsonProperty("AccountDetails")
  private String accountDetails = null;

  @JsonProperty("PositionLimits")
  private String positionLimits = null;

  @JsonProperty("PositionLimitType")
  private String positionLimitType = null;

  @JsonProperty("PositionLimitSettings")
  private String positionLimitSettings = null;

  @JsonProperty("PositionLimitValue")
  private String positionLimitValue = null;

  @JsonProperty("DateType")
  private String dateType = null;

  @JsonProperty("StatementsSchedule")
  private String statementsSchedule = null;

  @JsonProperty("StatementType")
  private String statementType = null;

  @JsonProperty("StatementTransactionType")
  private String statementTransactionType = null;

  @JsonProperty("StatementPeriod")
  private String statementPeriod = null;

  @JsonProperty("StatementReport")
  private String statementReport = null;

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility productInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
    return this;
  }

   /**
   *  
   * @return productInstanceReference
  **/
  @Schema(description = " ")
  public String getProductInstanceReference() {
    return productInstanceReference;
  }

  public void setProductInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility savingsAccountNumber(String savingsAccountNumber) {
    this.savingsAccountNumber = savingsAccountNumber;
    return this;
  }

   /**
   *  
   * @return savingsAccountNumber
  **/
  @Schema(description = " ")
  public String getSavingsAccountNumber() {
    return savingsAccountNumber;
  }

  public void setSavingsAccountNumber(String savingsAccountNumber) {
    this.savingsAccountNumber = savingsAccountNumber;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility customerReference(String customerReference) {
    this.customerReference = customerReference;
    return this;
  }

   /**
   *  
   * @return customerReference
  **/
  @Schema(description = " ")
  public String getCustomerReference() {
    return customerReference;
  }

  public void setCustomerReference(String customerReference) {
    this.customerReference = customerReference;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility bankBranchLocationReference(String bankBranchLocationReference) {
    this.bankBranchLocationReference = bankBranchLocationReference;
    return this;
  }

   /**
   *  
   * @return bankBranchLocationReference
  **/
  @Schema(description = " ")
  public String getBankBranchLocationReference() {
    return bankBranchLocationReference;
  }

  public void setBankBranchLocationReference(String bankBranchLocationReference) {
    this.bankBranchLocationReference = bankBranchLocationReference;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   *  
   * @return accountType
  **/
  @Schema(description = " ")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility accountCurrency(Currencycode accountCurrency) {
    this.accountCurrency = accountCurrency;
    return this;
  }

   /**
   * Get accountCurrency
   * @return accountCurrency
  **/
  @Schema(description = "")
  public Currencycode getAccountCurrency() {
    return accountCurrency;
  }

  public void setAccountCurrency(Currencycode accountCurrency) {
    this.accountCurrency = accountCurrency;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility taxReference(String taxReference) {
    this.taxReference = taxReference;
    return this;
  }

   /**
   *  
   * @return taxReference
  **/
  @Schema(description = " ")
  public String getTaxReference() {
    return taxReference;
  }

  public void setTaxReference(String taxReference) {
    this.taxReference = taxReference;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility entitlementOptionDefinition(String entitlementOptionDefinition) {
    this.entitlementOptionDefinition = entitlementOptionDefinition;
    return this;
  }

   /**
   *  
   * @return entitlementOptionDefinition
  **/
  @Schema(description = " ")
  public String getEntitlementOptionDefinition() {
    return entitlementOptionDefinition;
  }

  public void setEntitlementOptionDefinition(String entitlementOptionDefinition) {
    this.entitlementOptionDefinition = entitlementOptionDefinition;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility entitlementOptionSetting(String entitlementOptionSetting) {
    this.entitlementOptionSetting = entitlementOptionSetting;
    return this;
  }

   /**
   *  
   * @return entitlementOptionSetting
  **/
  @Schema(description = " ")
  public String getEntitlementOptionSetting() {
    return entitlementOptionSetting;
  }

  public void setEntitlementOptionSetting(String entitlementOptionSetting) {
    this.entitlementOptionSetting = entitlementOptionSetting;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility restrictionOptionDefinition(String restrictionOptionDefinition) {
    this.restrictionOptionDefinition = restrictionOptionDefinition;
    return this;
  }

   /**
   *  
   * @return restrictionOptionDefinition
  **/
  @Schema(description = " ")
  public String getRestrictionOptionDefinition() {
    return restrictionOptionDefinition;
  }

  public void setRestrictionOptionDefinition(String restrictionOptionDefinition) {
    this.restrictionOptionDefinition = restrictionOptionDefinition;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility restrictionOptionSetting(String restrictionOptionSetting) {
    this.restrictionOptionSetting = restrictionOptionSetting;
    return this;
  }

   /**
   *  
   * @return restrictionOptionSetting
  **/
  @Schema(description = " ")
  public String getRestrictionOptionSetting() {
    return restrictionOptionSetting;
  }

  public void setRestrictionOptionSetting(String restrictionOptionSetting) {
    this.restrictionOptionSetting = restrictionOptionSetting;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility associations(String associations) {
    this.associations = associations;
    return this;
  }

   /**
   *  
   * @return associations
  **/
  @Schema(description = " ")
  public String getAssociations() {
    return associations;
  }

  public void setAssociations(String associations) {
    this.associations = associations;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility associationType(String associationType) {
    this.associationType = associationType;
    return this;
  }

   /**
   *  
   * @return associationType
  **/
  @Schema(description = " ")
  public String getAssociationType() {
    return associationType;
  }

  public void setAssociationType(String associationType) {
    this.associationType = associationType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility associationObligationEntitlement(String associationObligationEntitlement) {
    this.associationObligationEntitlement = associationObligationEntitlement;
    return this;
  }

   /**
   *  
   * @return associationObligationEntitlement
  **/
  @Schema(description = " ")
  public String getAssociationObligationEntitlement() {
    return associationObligationEntitlement;
  }

  public void setAssociationObligationEntitlement(String associationObligationEntitlement) {
    this.associationObligationEntitlement = associationObligationEntitlement;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility associationReference(String associationReference) {
    this.associationReference = associationReference;
    return this;
  }

   /**
   *  
   * @return associationReference
  **/
  @Schema(description = " ")
  public String getAssociationReference() {
    return associationReference;
  }

  public void setAssociationReference(String associationReference) {
    this.associationReference = associationReference;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility linkedAccounts(String linkedAccounts) {
    this.linkedAccounts = linkedAccounts;
    return this;
  }

   /**
   *  
   * @return linkedAccounts
  **/
  @Schema(description = " ")
  public String getLinkedAccounts() {
    return linkedAccounts;
  }

  public void setLinkedAccounts(String linkedAccounts) {
    this.linkedAccounts = linkedAccounts;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility linkType(String linkType) {
    this.linkType = linkType;
    return this;
  }

   /**
   *  
   * @return linkType
  **/
  @Schema(description = " ")
  public String getLinkType() {
    return linkType;
  }

  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility accountDetails(String accountDetails) {
    this.accountDetails = accountDetails;
    return this;
  }

   /**
   *  
   * @return accountDetails
  **/
  @Schema(description = " ")
  public String getAccountDetails() {
    return accountDetails;
  }

  public void setAccountDetails(String accountDetails) {
    this.accountDetails = accountDetails;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility positionLimits(String positionLimits) {
    this.positionLimits = positionLimits;
    return this;
  }

   /**
   *  
   * @return positionLimits
  **/
  @Schema(description = " ")
  public String getPositionLimits() {
    return positionLimits;
  }

  public void setPositionLimits(String positionLimits) {
    this.positionLimits = positionLimits;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility positionLimitType(String positionLimitType) {
    this.positionLimitType = positionLimitType;
    return this;
  }

   /**
   *  
   * @return positionLimitType
  **/
  @Schema(description = " ")
  public String getPositionLimitType() {
    return positionLimitType;
  }

  public void setPositionLimitType(String positionLimitType) {
    this.positionLimitType = positionLimitType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility positionLimitSettings(String positionLimitSettings) {
    this.positionLimitSettings = positionLimitSettings;
    return this;
  }

   /**
   *  
   * @return positionLimitSettings
  **/
  @Schema(description = " ")
  public String getPositionLimitSettings() {
    return positionLimitSettings;
  }

  public void setPositionLimitSettings(String positionLimitSettings) {
    this.positionLimitSettings = positionLimitSettings;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility positionLimitValue(String positionLimitValue) {
    this.positionLimitValue = positionLimitValue;
    return this;
  }

   /**
   *  
   * @return positionLimitValue
  **/
  @Schema(description = " ")
  public String getPositionLimitValue() {
    return positionLimitValue;
  }

  public void setPositionLimitValue(String positionLimitValue) {
    this.positionLimitValue = positionLimitValue;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility dateType(String dateType) {
    this.dateType = dateType;
    return this;
  }

   /**
   *  
   * @return dateType
  **/
  @Schema(description = " ")
  public String getDateType() {
    return dateType;
  }

  public void setDateType(String dateType) {
    this.dateType = dateType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility statementsSchedule(String statementsSchedule) {
    this.statementsSchedule = statementsSchedule;
    return this;
  }

   /**
   *  
   * @return statementsSchedule
  **/
  @Schema(description = " ")
  public String getStatementsSchedule() {
    return statementsSchedule;
  }

  public void setStatementsSchedule(String statementsSchedule) {
    this.statementsSchedule = statementsSchedule;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility statementType(String statementType) {
    this.statementType = statementType;
    return this;
  }

   /**
   *  
   * @return statementType
  **/
  @Schema(description = " ")
  public String getStatementType() {
    return statementType;
  }

  public void setStatementType(String statementType) {
    this.statementType = statementType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility statementTransactionType(String statementTransactionType) {
    this.statementTransactionType = statementTransactionType;
    return this;
  }

   /**
   *  
   * @return statementTransactionType
  **/
  @Schema(description = " ")
  public String getStatementTransactionType() {
    return statementTransactionType;
  }

  public void setStatementTransactionType(String statementTransactionType) {
    this.statementTransactionType = statementTransactionType;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility statementPeriod(String statementPeriod) {
    this.statementPeriod = statementPeriod;
    return this;
  }

   /**
   *  
   * @return statementPeriod
  **/
  @Schema(description = " ")
  public String getStatementPeriod() {
    return statementPeriod;
  }

  public void setStatementPeriod(String statementPeriod) {
    this.statementPeriod = statementPeriod;
  }

  public UpdateSavingsAccountFacilityRequestSavingsAccountFacility statementReport(String statementReport) {
    this.statementReport = statementReport;
    return this;
  }

   /**
   *  
   * @return statementReport
  **/
  @Schema(description = " ")
  public String getStatementReport() {
    return statementReport;
  }

  public void setStatementReport(String statementReport) {
    this.statementReport = statementReport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSavingsAccountFacilityRequestSavingsAccountFacility updateSavingsAccountFacilityRequestSavingsAccountFacility = (UpdateSavingsAccountFacilityRequestSavingsAccountFacility) o;
    return Objects.equals(this.productInstanceReference, updateSavingsAccountFacilityRequestSavingsAccountFacility.productInstanceReference) &&
        Objects.equals(this.savingsAccountNumber, updateSavingsAccountFacilityRequestSavingsAccountFacility.savingsAccountNumber) &&
        Objects.equals(this.customerReference, updateSavingsAccountFacilityRequestSavingsAccountFacility.customerReference) &&
        Objects.equals(this.bankBranchLocationReference, updateSavingsAccountFacilityRequestSavingsAccountFacility.bankBranchLocationReference) &&
        Objects.equals(this.accountType, updateSavingsAccountFacilityRequestSavingsAccountFacility.accountType) &&
        Objects.equals(this.accountCurrency, updateSavingsAccountFacilityRequestSavingsAccountFacility.accountCurrency) &&
        Objects.equals(this.taxReference, updateSavingsAccountFacilityRequestSavingsAccountFacility.taxReference) &&
        Objects.equals(this.entitlementOptionDefinition, updateSavingsAccountFacilityRequestSavingsAccountFacility.entitlementOptionDefinition) &&
        Objects.equals(this.entitlementOptionSetting, updateSavingsAccountFacilityRequestSavingsAccountFacility.entitlementOptionSetting) &&
        Objects.equals(this.restrictionOptionDefinition, updateSavingsAccountFacilityRequestSavingsAccountFacility.restrictionOptionDefinition) &&
        Objects.equals(this.restrictionOptionSetting, updateSavingsAccountFacilityRequestSavingsAccountFacility.restrictionOptionSetting) &&
        Objects.equals(this.associations, updateSavingsAccountFacilityRequestSavingsAccountFacility.associations) &&
        Objects.equals(this.associationType, updateSavingsAccountFacilityRequestSavingsAccountFacility.associationType) &&
        Objects.equals(this.associationObligationEntitlement, updateSavingsAccountFacilityRequestSavingsAccountFacility.associationObligationEntitlement) &&
        Objects.equals(this.associationReference, updateSavingsAccountFacilityRequestSavingsAccountFacility.associationReference) &&
        Objects.equals(this.linkedAccounts, updateSavingsAccountFacilityRequestSavingsAccountFacility.linkedAccounts) &&
        Objects.equals(this.linkType, updateSavingsAccountFacilityRequestSavingsAccountFacility.linkType) &&
        Objects.equals(this.accountDetails, updateSavingsAccountFacilityRequestSavingsAccountFacility.accountDetails) &&
        Objects.equals(this.positionLimits, updateSavingsAccountFacilityRequestSavingsAccountFacility.positionLimits) &&
        Objects.equals(this.positionLimitType, updateSavingsAccountFacilityRequestSavingsAccountFacility.positionLimitType) &&
        Objects.equals(this.positionLimitSettings, updateSavingsAccountFacilityRequestSavingsAccountFacility.positionLimitSettings) &&
        Objects.equals(this.positionLimitValue, updateSavingsAccountFacilityRequestSavingsAccountFacility.positionLimitValue) &&
        Objects.equals(this.dateType, updateSavingsAccountFacilityRequestSavingsAccountFacility.dateType) &&
        Objects.equals(this.statementsSchedule, updateSavingsAccountFacilityRequestSavingsAccountFacility.statementsSchedule) &&
        Objects.equals(this.statementType, updateSavingsAccountFacilityRequestSavingsAccountFacility.statementType) &&
        Objects.equals(this.statementTransactionType, updateSavingsAccountFacilityRequestSavingsAccountFacility.statementTransactionType) &&
        Objects.equals(this.statementPeriod, updateSavingsAccountFacilityRequestSavingsAccountFacility.statementPeriod) &&
        Objects.equals(this.statementReport, updateSavingsAccountFacilityRequestSavingsAccountFacility.statementReport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productInstanceReference, savingsAccountNumber, customerReference, bankBranchLocationReference, accountType, accountCurrency, taxReference, entitlementOptionDefinition, entitlementOptionSetting, restrictionOptionDefinition, restrictionOptionSetting, associations, associationType, associationObligationEntitlement, associationReference, linkedAccounts, linkType, accountDetails, positionLimits, positionLimitType, positionLimitSettings, positionLimitValue, dateType, statementsSchedule, statementType, statementTransactionType, statementPeriod, statementReport);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSavingsAccountFacilityRequestSavingsAccountFacility {\n");
    
    sb.append("    productInstanceReference: ").append(toIndentedString(productInstanceReference)).append("\n");
    sb.append("    savingsAccountNumber: ").append(toIndentedString(savingsAccountNumber)).append("\n");
    sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
    sb.append("    bankBranchLocationReference: ").append(toIndentedString(bankBranchLocationReference)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    accountCurrency: ").append(toIndentedString(accountCurrency)).append("\n");
    sb.append("    taxReference: ").append(toIndentedString(taxReference)).append("\n");
    sb.append("    entitlementOptionDefinition: ").append(toIndentedString(entitlementOptionDefinition)).append("\n");
    sb.append("    entitlementOptionSetting: ").append(toIndentedString(entitlementOptionSetting)).append("\n");
    sb.append("    restrictionOptionDefinition: ").append(toIndentedString(restrictionOptionDefinition)).append("\n");
    sb.append("    restrictionOptionSetting: ").append(toIndentedString(restrictionOptionSetting)).append("\n");
    sb.append("    associations: ").append(toIndentedString(associations)).append("\n");
    sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
    sb.append("    associationObligationEntitlement: ").append(toIndentedString(associationObligationEntitlement)).append("\n");
    sb.append("    associationReference: ").append(toIndentedString(associationReference)).append("\n");
    sb.append("    linkedAccounts: ").append(toIndentedString(linkedAccounts)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    accountDetails: ").append(toIndentedString(accountDetails)).append("\n");
    sb.append("    positionLimits: ").append(toIndentedString(positionLimits)).append("\n");
    sb.append("    positionLimitType: ").append(toIndentedString(positionLimitType)).append("\n");
    sb.append("    positionLimitSettings: ").append(toIndentedString(positionLimitSettings)).append("\n");
    sb.append("    positionLimitValue: ").append(toIndentedString(positionLimitValue)).append("\n");
    sb.append("    dateType: ").append(toIndentedString(dateType)).append("\n");
    sb.append("    statementsSchedule: ").append(toIndentedString(statementsSchedule)).append("\n");
    sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
    sb.append("    statementTransactionType: ").append(toIndentedString(statementTransactionType)).append("\n");
    sb.append("    statementPeriod: ").append(toIndentedString(statementPeriod)).append("\n");
    sb.append("    statementReport: ").append(toIndentedString(statementReport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
