/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hs.sample.k.savings.model;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;


import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Output: InBQ Initialize a payment transaction (can be single or repeating)
 */
@Schema(description = "Output: InBQ Initialize a payment transaction (can be single or repeating)")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class InitiatePaymentsResponse {
  @JsonProperty("SavingsAccountFacility")
  private InitiatePaymentsResponseSavingsAccountFacility savingsAccountFacility = null;

  @JsonProperty("Payments")
  private InitiatePaymentsResponsePayments payments = null;

  public InitiatePaymentsResponse savingsAccountFacility(InitiatePaymentsResponseSavingsAccountFacility savingsAccountFacility) {
    this.savingsAccountFacility = savingsAccountFacility;
    return this;
  }

   /**
   * Get savingsAccountFacility
   * @return savingsAccountFacility
  **/
  @Schema(description = "")
  public InitiatePaymentsResponseSavingsAccountFacility getSavingsAccountFacility() {
    return savingsAccountFacility;
  }

  public void setSavingsAccountFacility(InitiatePaymentsResponseSavingsAccountFacility savingsAccountFacility) {
    this.savingsAccountFacility = savingsAccountFacility;
  }

  public InitiatePaymentsResponse payments(InitiatePaymentsResponsePayments payments) {
    this.payments = payments;
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  @Schema(description = "")
  public InitiatePaymentsResponsePayments getPayments() {
    return payments;
  }

  public void setPayments(InitiatePaymentsResponsePayments payments) {
    this.payments = payments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiatePaymentsResponse initiatePaymentsResponse = (InitiatePaymentsResponse) o;
    return Objects.equals(this.savingsAccountFacility, initiatePaymentsResponse.savingsAccountFacility) &&
        Objects.equals(this.payments, initiatePaymentsResponse.payments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(savingsAccountFacility, payments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiatePaymentsResponse {\n");
    
    sb.append("    savingsAccountFacility: ").append(toIndentedString(savingsAccountFacility)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
