version: '3.9'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  mysql-db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hosuk
      MYSQL_DATABASE: hosuk
      MYSQL_USER: hosuk
      MYSQL_PASSWORD: hosuk
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
  front:
    image: hosuk/project-k-front
    expose:
      - "80"
  apiserver:
    image: hosuk/project-k-apiserver
    expose:
      - "8080"
    ports:
      - "8080:8080"  # API 서버의 포트를 설정하세요
  dm-savings-account:
    image: hosuk/project-k-dm-savings-account
    expose:
      - "8080"
  dm-party-reference-data-direcotry:
    image: hosuk/project-k-dm-party-reference-data-direcotry
    expose:
      - "8080"
