version: '3.9'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  front:
    image: hosuk/project-k-front
    expose:
      - "80"
  apiserver:
    image: hosuk/project-k-apiserver
    expose:
      - "8080"
    ports:
      - "8080:8080"  # API 서버의 포트를 설정하세요
  dm-savings-account:
    image: hosuk/project-k-dm-savings-account
    expose:
      - "8080"
  dm-party-reference-data-direcotry:
    image: hosuk/project-k-dm-party-reference-data-direcotry
    expose:
      - "8080"
