version: '3.9'

# Default 네트워크인 Bridge
#networks:
#  gitea:
#    external: false


services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  mysql-db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hosuk
      MYSQL_DATABASE: hosuk
      MYSQL_USER: hosuk
      MYSQL_PASSWORD: hosuk
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
  gitea:
    image: gitea/gitea:1.22.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=giteadb
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    depends_on:
      - mysql-db  # 서비스간의 종속성 순서대로 서비스를 시작
