/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hs.sample.k.apiserver.model;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;





import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ExecuteServiceFeesRequestServiceFees
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class ExecuteServiceFeesRequestServiceFees {
  @JsonProperty("FeeConfigurationProfile")
  private String feeConfigurationProfile = null;

  @JsonProperty("FeeType")
  private String feeType = null;

  @JsonProperty("FeeApplicationRecord")
  private String feeApplicationRecord = null;

  @JsonProperty("FeeTransaction")
  private String feeTransaction = null;

  @JsonProperty("TransactionDescription")
  private String transactionDescription = null;

  @JsonProperty("TransactionFeeType")
  private String transactionFeeType = null;

  @JsonProperty("FeeProjectionsandCommitments")
  private String feeProjectionsandCommitments = null;

  @JsonProperty("ProjectedTransactionDescription")
  private String projectedTransactionDescription = null;

  @JsonProperty("ProjectedTransactionFeeType")
  private String projectedTransactionFeeType = null;

  @JsonProperty("AccrualFeeType")
  private String accrualFeeType = null;

  public ExecuteServiceFeesRequestServiceFees feeConfigurationProfile(String feeConfigurationProfile) {
    this.feeConfigurationProfile = feeConfigurationProfile;
    return this;
  }

   /**
   *  
   * @return feeConfigurationProfile
  **/
  @Schema(description = " ")
  public String getFeeConfigurationProfile() {
    return feeConfigurationProfile;
  }

  public void setFeeConfigurationProfile(String feeConfigurationProfile) {
    this.feeConfigurationProfile = feeConfigurationProfile;
  }

  public ExecuteServiceFeesRequestServiceFees feeType(String feeType) {
    this.feeType = feeType;
    return this;
  }

   /**
   *  
   * @return feeType
  **/
  @Schema(description = " ")
  public String getFeeType() {
    return feeType;
  }

  public void setFeeType(String feeType) {
    this.feeType = feeType;
  }

  public ExecuteServiceFeesRequestServiceFees feeApplicationRecord(String feeApplicationRecord) {
    this.feeApplicationRecord = feeApplicationRecord;
    return this;
  }

   /**
   *  
   * @return feeApplicationRecord
  **/
  @Schema(description = " ")
  public String getFeeApplicationRecord() {
    return feeApplicationRecord;
  }

  public void setFeeApplicationRecord(String feeApplicationRecord) {
    this.feeApplicationRecord = feeApplicationRecord;
  }

  public ExecuteServiceFeesRequestServiceFees feeTransaction(String feeTransaction) {
    this.feeTransaction = feeTransaction;
    return this;
  }

   /**
   *  
   * @return feeTransaction
  **/
  @Schema(description = " ")
  public String getFeeTransaction() {
    return feeTransaction;
  }

  public void setFeeTransaction(String feeTransaction) {
    this.feeTransaction = feeTransaction;
  }

  public ExecuteServiceFeesRequestServiceFees transactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
    return this;
  }

   /**
   *  
   * @return transactionDescription
  **/
  @Schema(description = " ")
  public String getTransactionDescription() {
    return transactionDescription;
  }

  public void setTransactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
  }

  public ExecuteServiceFeesRequestServiceFees transactionFeeType(String transactionFeeType) {
    this.transactionFeeType = transactionFeeType;
    return this;
  }

   /**
   *  
   * @return transactionFeeType
  **/
  @Schema(description = " ")
  public String getTransactionFeeType() {
    return transactionFeeType;
  }

  public void setTransactionFeeType(String transactionFeeType) {
    this.transactionFeeType = transactionFeeType;
  }

  public ExecuteServiceFeesRequestServiceFees feeProjectionsandCommitments(String feeProjectionsandCommitments) {
    this.feeProjectionsandCommitments = feeProjectionsandCommitments;
    return this;
  }

   /**
   *  
   * @return feeProjectionsandCommitments
  **/
  @Schema(description = " ")
  public String getFeeProjectionsandCommitments() {
    return feeProjectionsandCommitments;
  }

  public void setFeeProjectionsandCommitments(String feeProjectionsandCommitments) {
    this.feeProjectionsandCommitments = feeProjectionsandCommitments;
  }

  public ExecuteServiceFeesRequestServiceFees projectedTransactionDescription(String projectedTransactionDescription) {
    this.projectedTransactionDescription = projectedTransactionDescription;
    return this;
  }

   /**
   *  
   * @return projectedTransactionDescription
  **/
  @Schema(description = " ")
  public String getProjectedTransactionDescription() {
    return projectedTransactionDescription;
  }

  public void setProjectedTransactionDescription(String projectedTransactionDescription) {
    this.projectedTransactionDescription = projectedTransactionDescription;
  }

  public ExecuteServiceFeesRequestServiceFees projectedTransactionFeeType(String projectedTransactionFeeType) {
    this.projectedTransactionFeeType = projectedTransactionFeeType;
    return this;
  }

   /**
   *  
   * @return projectedTransactionFeeType
  **/
  @Schema(description = " ")
  public String getProjectedTransactionFeeType() {
    return projectedTransactionFeeType;
  }

  public void setProjectedTransactionFeeType(String projectedTransactionFeeType) {
    this.projectedTransactionFeeType = projectedTransactionFeeType;
  }

  public ExecuteServiceFeesRequestServiceFees accrualFeeType(String accrualFeeType) {
    this.accrualFeeType = accrualFeeType;
    return this;
  }

   /**
   *  
   * @return accrualFeeType
  **/
  @Schema(description = " ")
  public String getAccrualFeeType() {
    return accrualFeeType;
  }

  public void setAccrualFeeType(String accrualFeeType) {
    this.accrualFeeType = accrualFeeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteServiceFeesRequestServiceFees executeServiceFeesRequestServiceFees = (ExecuteServiceFeesRequestServiceFees) o;
    return Objects.equals(this.feeConfigurationProfile, executeServiceFeesRequestServiceFees.feeConfigurationProfile) &&
        Objects.equals(this.feeType, executeServiceFeesRequestServiceFees.feeType) &&
        Objects.equals(this.feeApplicationRecord, executeServiceFeesRequestServiceFees.feeApplicationRecord) &&
        Objects.equals(this.feeTransaction, executeServiceFeesRequestServiceFees.feeTransaction) &&
        Objects.equals(this.transactionDescription, executeServiceFeesRequestServiceFees.transactionDescription) &&
        Objects.equals(this.transactionFeeType, executeServiceFeesRequestServiceFees.transactionFeeType) &&
        Objects.equals(this.feeProjectionsandCommitments, executeServiceFeesRequestServiceFees.feeProjectionsandCommitments) &&
        Objects.equals(this.projectedTransactionDescription, executeServiceFeesRequestServiceFees.projectedTransactionDescription) &&
        Objects.equals(this.projectedTransactionFeeType, executeServiceFeesRequestServiceFees.projectedTransactionFeeType) &&
        Objects.equals(this.accrualFeeType, executeServiceFeesRequestServiceFees.accrualFeeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feeConfigurationProfile, feeType, feeApplicationRecord, feeTransaction, transactionDescription, transactionFeeType, feeProjectionsandCommitments, projectedTransactionDescription, projectedTransactionFeeType, accrualFeeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteServiceFeesRequestServiceFees {\n");
    
    sb.append("    feeConfigurationProfile: ").append(toIndentedString(feeConfigurationProfile)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("    feeApplicationRecord: ").append(toIndentedString(feeApplicationRecord)).append("\n");
    sb.append("    feeTransaction: ").append(toIndentedString(feeTransaction)).append("\n");
    sb.append("    transactionDescription: ").append(toIndentedString(transactionDescription)).append("\n");
    sb.append("    transactionFeeType: ").append(toIndentedString(transactionFeeType)).append("\n");
    sb.append("    feeProjectionsandCommitments: ").append(toIndentedString(feeProjectionsandCommitments)).append("\n");
    sb.append("    projectedTransactionDescription: ").append(toIndentedString(projectedTransactionDescription)).append("\n");
    sb.append("    projectedTransactionFeeType: ").append(toIndentedString(projectedTransactionFeeType)).append("\n");
    sb.append("    accrualFeeType: ").append(toIndentedString(accrualFeeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
