/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hs.sample.k.apiserver.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;
import java.util.Arrays;





import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InitiateAccountLienResponseAccountLien
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class InitiateAccountLienResponseAccountLien {
  @JsonProperty("LienDefinition")
  private String lienDefinition = null;

  @JsonProperty("LienRecord")
  private String lienRecord = null;

  public InitiateAccountLienResponseAccountLien lienDefinition(String lienDefinition) {
    this.lienDefinition = lienDefinition;
    return this;
  }

   /**
   *  
   * @return lienDefinition
  **/
  @Schema(description = " ")
  public String getLienDefinition() {
    return lienDefinition;
  }

  public void setLienDefinition(String lienDefinition) {
    this.lienDefinition = lienDefinition;
  }

  public InitiateAccountLienResponseAccountLien lienRecord(String lienRecord) {
    this.lienRecord = lienRecord;
    return this;
  }

   /**
   *  
   * @return lienRecord
  **/
  @Schema(description = " ")
  public String getLienRecord() {
    return lienRecord;
  }

  public void setLienRecord(String lienRecord) {
    this.lienRecord = lienRecord;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateAccountLienResponseAccountLien initiateAccountLienResponseAccountLien = (InitiateAccountLienResponseAccountLien) o;
    return Objects.equals(this.lienDefinition, initiateAccountLienResponseAccountLien.lienDefinition) &&
        Objects.equals(this.lienRecord, initiateAccountLienResponseAccountLien.lienRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lienDefinition, lienRecord);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateAccountLienResponseAccountLien {\n");
    
    sb.append("    lienDefinition: ").append(toIndentedString(lienDefinition)).append("\n");
    sb.append("    lienRecord: ").append(toIndentedString(lienRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
