// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package com.kb.sample.savings.domain.config;

/**
 * Provide an interface for root entities.
 *
 * @Generated
 *
 */
public interface RootEntity  {

  public abstract Long getId();
  public abstract void setId(Long id);

}
