/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.sample.savings.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import java.util.Objects;


import io.swagger.v3.oas.annotations.media.Schema;
//import org.threeten.bp.LocalDate;
/**
 * ExecutePaymentsRequestPayments
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class ExecutePaymentsRequestPayments {
  @JsonProperty("PaymentTransaction")
  private String paymentTransaction = null;

  @JsonProperty("PaymentTransactionType")
  private String paymentTransactionType = null;

  @JsonProperty("PaymentTransactionPayeeReference")
  private String paymentTransactionPayeeReference = null;

  @JsonProperty("PaymentTransactionPayeeAccountReference")
  private String paymentTransactionPayeeAccountReference = null;

  @JsonProperty("PaymentTransactionPayeeBankReference")
  private String paymentTransactionPayeeBankReference = null;

  @JsonProperty("PaymentTransactionAmount")
  private Amount paymentTransactionAmount = null;

  @JsonProperty("PaymentTransactionFeeType")
  private String paymentTransactionFeeType = null;

  @JsonProperty("PaymentTransactionFeeCharge")
  private String paymentTransactionFeeCharge = null;

  @JsonProperty("PaymentTransactionDate")
  private LocalDate paymentTransactionDate = null;

  @JsonProperty("PaymentTransactionPaymentMechanism")
  private String paymentTransactionPaymentMechanism = null;

  @JsonProperty("PaymentTransactionPaymentPurpose")
  private String paymentTransactionPaymentPurpose = null;

  @JsonProperty("PaymentTransactionBankBranchLocationReference")
  private String paymentTransactionBankBranchLocationReference = null;

  @JsonProperty("PaymentTransactionStatus")
  private String paymentTransactionStatus = null;

  public ExecutePaymentsRequestPayments paymentTransaction(String paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
    return this;
  }

   /**
   *  
   * @return paymentTransaction
  **/
  @Schema(description = " ")
  public String getPaymentTransaction() {
    return paymentTransaction;
  }

  public void setPaymentTransaction(String paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
  }

  public ExecutePaymentsRequestPayments paymentTransactionType(String paymentTransactionType) {
    this.paymentTransactionType = paymentTransactionType;
    return this;
  }

   /**
   *  
   * @return paymentTransactionType
  **/
  @Schema(description = " ")
  public String getPaymentTransactionType() {
    return paymentTransactionType;
  }

  public void setPaymentTransactionType(String paymentTransactionType) {
    this.paymentTransactionType = paymentTransactionType;
  }

  public ExecutePaymentsRequestPayments paymentTransactionPayeeReference(String paymentTransactionPayeeReference) {
    this.paymentTransactionPayeeReference = paymentTransactionPayeeReference;
    return this;
  }

   /**
   *  
   * @return paymentTransactionPayeeReference
  **/
  @Schema(description = " ")
  public String getPaymentTransactionPayeeReference() {
    return paymentTransactionPayeeReference;
  }

  public void setPaymentTransactionPayeeReference(String paymentTransactionPayeeReference) {
    this.paymentTransactionPayeeReference = paymentTransactionPayeeReference;
  }

  public ExecutePaymentsRequestPayments paymentTransactionPayeeAccountReference(String paymentTransactionPayeeAccountReference) {
    this.paymentTransactionPayeeAccountReference = paymentTransactionPayeeAccountReference;
    return this;
  }

   /**
   *  
   * @return paymentTransactionPayeeAccountReference
  **/
  @Schema(description = " ")
  public String getPaymentTransactionPayeeAccountReference() {
    return paymentTransactionPayeeAccountReference;
  }

  public void setPaymentTransactionPayeeAccountReference(String paymentTransactionPayeeAccountReference) {
    this.paymentTransactionPayeeAccountReference = paymentTransactionPayeeAccountReference;
  }

  public ExecutePaymentsRequestPayments paymentTransactionPayeeBankReference(String paymentTransactionPayeeBankReference) {
    this.paymentTransactionPayeeBankReference = paymentTransactionPayeeBankReference;
    return this;
  }

   /**
   *  
   * @return paymentTransactionPayeeBankReference
  **/
  @Schema(description = " ")
  public String getPaymentTransactionPayeeBankReference() {
    return paymentTransactionPayeeBankReference;
  }

  public void setPaymentTransactionPayeeBankReference(String paymentTransactionPayeeBankReference) {
    this.paymentTransactionPayeeBankReference = paymentTransactionPayeeBankReference;
  }

  public ExecutePaymentsRequestPayments paymentTransactionAmount(Amount paymentTransactionAmount) {
    this.paymentTransactionAmount = paymentTransactionAmount;
    return this;
  }

   /**
   * Get paymentTransactionAmount
   * @return paymentTransactionAmount
  **/
  @Schema(description = "")
  public Amount getPaymentTransactionAmount() {
    return paymentTransactionAmount;
  }

  public void setPaymentTransactionAmount(Amount paymentTransactionAmount) {
    this.paymentTransactionAmount = paymentTransactionAmount;
  }

  public ExecutePaymentsRequestPayments paymentTransactionFeeType(String paymentTransactionFeeType) {
    this.paymentTransactionFeeType = paymentTransactionFeeType;
    return this;
  }

   /**
   *  
   * @return paymentTransactionFeeType
  **/
  @Schema(description = " ")
  public String getPaymentTransactionFeeType() {
    return paymentTransactionFeeType;
  }

  public void setPaymentTransactionFeeType(String paymentTransactionFeeType) {
    this.paymentTransactionFeeType = paymentTransactionFeeType;
  }

  public ExecutePaymentsRequestPayments paymentTransactionFeeCharge(String paymentTransactionFeeCharge) {
    this.paymentTransactionFeeCharge = paymentTransactionFeeCharge;
    return this;
  }

   /**
   *  
   * @return paymentTransactionFeeCharge
  **/
  @Schema(description = " ")
  public String getPaymentTransactionFeeCharge() {
    return paymentTransactionFeeCharge;
  }

  public void setPaymentTransactionFeeCharge(String paymentTransactionFeeCharge) {
    this.paymentTransactionFeeCharge = paymentTransactionFeeCharge;
  }

  public ExecutePaymentsRequestPayments paymentTransactionDate(LocalDate paymentTransactionDate) {
    this.paymentTransactionDate = paymentTransactionDate;
    return this;
  }

   /**
   * Get paymentTransactionDate
   * @return paymentTransactionDate
  **/
  @Schema(description = "")
  public LocalDate getPaymentTransactionDate() {
    return paymentTransactionDate;
  }

  public void setPaymentTransactionDate(LocalDate paymentTransactionDate) {
    this.paymentTransactionDate = paymentTransactionDate;
  }

  public ExecutePaymentsRequestPayments paymentTransactionPaymentMechanism(String paymentTransactionPaymentMechanism) {
    this.paymentTransactionPaymentMechanism = paymentTransactionPaymentMechanism;
    return this;
  }

   /**
   *  
   * @return paymentTransactionPaymentMechanism
  **/
  @Schema(description = " ")
  public String getPaymentTransactionPaymentMechanism() {
    return paymentTransactionPaymentMechanism;
  }

  public void setPaymentTransactionPaymentMechanism(String paymentTransactionPaymentMechanism) {
    this.paymentTransactionPaymentMechanism = paymentTransactionPaymentMechanism;
  }

  public ExecutePaymentsRequestPayments paymentTransactionPaymentPurpose(String paymentTransactionPaymentPurpose) {
    this.paymentTransactionPaymentPurpose = paymentTransactionPaymentPurpose;
    return this;
  }

   /**
   *  
   * @return paymentTransactionPaymentPurpose
  **/
  @Schema(description = " ")
  public String getPaymentTransactionPaymentPurpose() {
    return paymentTransactionPaymentPurpose;
  }

  public void setPaymentTransactionPaymentPurpose(String paymentTransactionPaymentPurpose) {
    this.paymentTransactionPaymentPurpose = paymentTransactionPaymentPurpose;
  }

  public ExecutePaymentsRequestPayments paymentTransactionBankBranchLocationReference(String paymentTransactionBankBranchLocationReference) {
    this.paymentTransactionBankBranchLocationReference = paymentTransactionBankBranchLocationReference;
    return this;
  }

   /**
   *  
   * @return paymentTransactionBankBranchLocationReference
  **/
  @Schema(description = " ")
  public String getPaymentTransactionBankBranchLocationReference() {
    return paymentTransactionBankBranchLocationReference;
  }

  public void setPaymentTransactionBankBranchLocationReference(String paymentTransactionBankBranchLocationReference) {
    this.paymentTransactionBankBranchLocationReference = paymentTransactionBankBranchLocationReference;
  }

  public ExecutePaymentsRequestPayments paymentTransactionStatus(String paymentTransactionStatus) {
    this.paymentTransactionStatus = paymentTransactionStatus;
    return this;
  }

   /**
   *  
   * @return paymentTransactionStatus
  **/
  @Schema(description = " ")
  public String getPaymentTransactionStatus() {
    return paymentTransactionStatus;
  }

  public void setPaymentTransactionStatus(String paymentTransactionStatus) {
    this.paymentTransactionStatus = paymentTransactionStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutePaymentsRequestPayments executePaymentsRequestPayments = (ExecutePaymentsRequestPayments) o;
    return Objects.equals(this.paymentTransaction, executePaymentsRequestPayments.paymentTransaction) &&
        Objects.equals(this.paymentTransactionType, executePaymentsRequestPayments.paymentTransactionType) &&
        Objects.equals(this.paymentTransactionPayeeReference, executePaymentsRequestPayments.paymentTransactionPayeeReference) &&
        Objects.equals(this.paymentTransactionPayeeAccountReference, executePaymentsRequestPayments.paymentTransactionPayeeAccountReference) &&
        Objects.equals(this.paymentTransactionPayeeBankReference, executePaymentsRequestPayments.paymentTransactionPayeeBankReference) &&
        Objects.equals(this.paymentTransactionAmount, executePaymentsRequestPayments.paymentTransactionAmount) &&
        Objects.equals(this.paymentTransactionFeeType, executePaymentsRequestPayments.paymentTransactionFeeType) &&
        Objects.equals(this.paymentTransactionFeeCharge, executePaymentsRequestPayments.paymentTransactionFeeCharge) &&
        Objects.equals(this.paymentTransactionDate, executePaymentsRequestPayments.paymentTransactionDate) &&
        Objects.equals(this.paymentTransactionPaymentMechanism, executePaymentsRequestPayments.paymentTransactionPaymentMechanism) &&
        Objects.equals(this.paymentTransactionPaymentPurpose, executePaymentsRequestPayments.paymentTransactionPaymentPurpose) &&
        Objects.equals(this.paymentTransactionBankBranchLocationReference, executePaymentsRequestPayments.paymentTransactionBankBranchLocationReference) &&
        Objects.equals(this.paymentTransactionStatus, executePaymentsRequestPayments.paymentTransactionStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentTransaction, paymentTransactionType, paymentTransactionPayeeReference, paymentTransactionPayeeAccountReference, paymentTransactionPayeeBankReference, paymentTransactionAmount, paymentTransactionFeeType, paymentTransactionFeeCharge, paymentTransactionDate, paymentTransactionPaymentMechanism, paymentTransactionPaymentPurpose, paymentTransactionBankBranchLocationReference, paymentTransactionStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutePaymentsRequestPayments {\n");
    
    sb.append("    paymentTransaction: ").append(toIndentedString(paymentTransaction)).append("\n");
    sb.append("    paymentTransactionType: ").append(toIndentedString(paymentTransactionType)).append("\n");
    sb.append("    paymentTransactionPayeeReference: ").append(toIndentedString(paymentTransactionPayeeReference)).append("\n");
    sb.append("    paymentTransactionPayeeAccountReference: ").append(toIndentedString(paymentTransactionPayeeAccountReference)).append("\n");
    sb.append("    paymentTransactionPayeeBankReference: ").append(toIndentedString(paymentTransactionPayeeBankReference)).append("\n");
    sb.append("    paymentTransactionAmount: ").append(toIndentedString(paymentTransactionAmount)).append("\n");
    sb.append("    paymentTransactionFeeType: ").append(toIndentedString(paymentTransactionFeeType)).append("\n");
    sb.append("    paymentTransactionFeeCharge: ").append(toIndentedString(paymentTransactionFeeCharge)).append("\n");
    sb.append("    paymentTransactionDate: ").append(toIndentedString(paymentTransactionDate)).append("\n");
    sb.append("    paymentTransactionPaymentMechanism: ").append(toIndentedString(paymentTransactionPaymentMechanism)).append("\n");
    sb.append("    paymentTransactionPaymentPurpose: ").append(toIndentedString(paymentTransactionPaymentPurpose)).append("\n");
    sb.append("    paymentTransactionBankBranchLocationReference: ").append(toIndentedString(paymentTransactionBankBranchLocationReference)).append("\n");
    sb.append("    paymentTransactionStatus: ").append(toIndentedString(paymentTransactionStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
