/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.sample.savings.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;


import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RetrieveInterestResponseInterest
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class RetrieveInterestResponseInterest {
  @JsonProperty("InterestRateType")
  private String interestRateType = null;

  @JsonProperty("InterestRateApplicationSchedule")
  private Rate interestRateApplicationSchedule = null;

  @JsonProperty("InterestRateConfiguration")
  private Rate interestRateConfiguration = null;

  @JsonProperty("InterestApplicationRecord")
  private String interestApplicationRecord = null;

  @JsonProperty("InterestTransaction")
  private String interestTransaction = null;

  @JsonProperty("TransactionDescription")
  private String transactionDescription = null;

  @JsonProperty("TransactionRateType")
  private String transactionRateType = null;

  @JsonProperty("TransactionInterestCharge")
  private String transactionInterestCharge = null;

  @JsonProperty("InterestAccrualAmount")
  private Amount interestAccrualAmount = null;

  @JsonProperty("InterestAccrualType")
  private String interestAccrualType = null;

  @JsonProperty("InterestAccrualCharge")
  private String interestAccrualCharge = null;

  public RetrieveInterestResponseInterest interestRateType(String interestRateType) {
    this.interestRateType = interestRateType;
    return this;
  }

   /**
   *  
   * @return interestRateType
  **/
  @Schema(description = " ")
  public String getInterestRateType() {
    return interestRateType;
  }

  public void setInterestRateType(String interestRateType) {
    this.interestRateType = interestRateType;
  }

  public RetrieveInterestResponseInterest interestRateApplicationSchedule(Rate interestRateApplicationSchedule) {
    this.interestRateApplicationSchedule = interestRateApplicationSchedule;
    return this;
  }

   /**
   * Get interestRateApplicationSchedule
   * @return interestRateApplicationSchedule
  **/
  @Schema(description = "")
  public Rate getInterestRateApplicationSchedule() {
    return interestRateApplicationSchedule;
  }

  public void setInterestRateApplicationSchedule(Rate interestRateApplicationSchedule) {
    this.interestRateApplicationSchedule = interestRateApplicationSchedule;
  }

  public RetrieveInterestResponseInterest interestRateConfiguration(Rate interestRateConfiguration) {
    this.interestRateConfiguration = interestRateConfiguration;
    return this;
  }

   /**
   * Get interestRateConfiguration
   * @return interestRateConfiguration
  **/
  @Schema(description = "")
  public Rate getInterestRateConfiguration() {
    return interestRateConfiguration;
  }

  public void setInterestRateConfiguration(Rate interestRateConfiguration) {
    this.interestRateConfiguration = interestRateConfiguration;
  }

  public RetrieveInterestResponseInterest interestApplicationRecord(String interestApplicationRecord) {
    this.interestApplicationRecord = interestApplicationRecord;
    return this;
  }

   /**
   *  
   * @return interestApplicationRecord
  **/
  @Schema(description = " ")
  public String getInterestApplicationRecord() {
    return interestApplicationRecord;
  }

  public void setInterestApplicationRecord(String interestApplicationRecord) {
    this.interestApplicationRecord = interestApplicationRecord;
  }

  public RetrieveInterestResponseInterest interestTransaction(String interestTransaction) {
    this.interestTransaction = interestTransaction;
    return this;
  }

   /**
   *  
   * @return interestTransaction
  **/
  @Schema(description = " ")
  public String getInterestTransaction() {
    return interestTransaction;
  }

  public void setInterestTransaction(String interestTransaction) {
    this.interestTransaction = interestTransaction;
  }

  public RetrieveInterestResponseInterest transactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
    return this;
  }

   /**
   *  
   * @return transactionDescription
  **/
  @Schema(description = " ")
  public String getTransactionDescription() {
    return transactionDescription;
  }

  public void setTransactionDescription(String transactionDescription) {
    this.transactionDescription = transactionDescription;
  }

  public RetrieveInterestResponseInterest transactionRateType(String transactionRateType) {
    this.transactionRateType = transactionRateType;
    return this;
  }

   /**
   *  
   * @return transactionRateType
  **/
  @Schema(description = " ")
  public String getTransactionRateType() {
    return transactionRateType;
  }

  public void setTransactionRateType(String transactionRateType) {
    this.transactionRateType = transactionRateType;
  }

  public RetrieveInterestResponseInterest transactionInterestCharge(String transactionInterestCharge) {
    this.transactionInterestCharge = transactionInterestCharge;
    return this;
  }

   /**
   *  
   * @return transactionInterestCharge
  **/
  @Schema(description = " ")
  public String getTransactionInterestCharge() {
    return transactionInterestCharge;
  }

  public void setTransactionInterestCharge(String transactionInterestCharge) {
    this.transactionInterestCharge = transactionInterestCharge;
  }

  public RetrieveInterestResponseInterest interestAccrualAmount(Amount interestAccrualAmount) {
    this.interestAccrualAmount = interestAccrualAmount;
    return this;
  }

   /**
   * Get interestAccrualAmount
   * @return interestAccrualAmount
  **/
  @Schema(description = "")
  public Amount getInterestAccrualAmount() {
    return interestAccrualAmount;
  }

  public void setInterestAccrualAmount(Amount interestAccrualAmount) {
    this.interestAccrualAmount = interestAccrualAmount;
  }

  public RetrieveInterestResponseInterest interestAccrualType(String interestAccrualType) {
    this.interestAccrualType = interestAccrualType;
    return this;
  }

   /**
   *  
   * @return interestAccrualType
  **/
  @Schema(description = " ")
  public String getInterestAccrualType() {
    return interestAccrualType;
  }

  public void setInterestAccrualType(String interestAccrualType) {
    this.interestAccrualType = interestAccrualType;
  }

  public RetrieveInterestResponseInterest interestAccrualCharge(String interestAccrualCharge) {
    this.interestAccrualCharge = interestAccrualCharge;
    return this;
  }

   /**
   *  
   * @return interestAccrualCharge
  **/
  @Schema(description = " ")
  public String getInterestAccrualCharge() {
    return interestAccrualCharge;
  }

  public void setInterestAccrualCharge(String interestAccrualCharge) {
    this.interestAccrualCharge = interestAccrualCharge;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveInterestResponseInterest retrieveInterestResponseInterest = (RetrieveInterestResponseInterest) o;
    return Objects.equals(this.interestRateType, retrieveInterestResponseInterest.interestRateType) &&
        Objects.equals(this.interestRateApplicationSchedule, retrieveInterestResponseInterest.interestRateApplicationSchedule) &&
        Objects.equals(this.interestRateConfiguration, retrieveInterestResponseInterest.interestRateConfiguration) &&
        Objects.equals(this.interestApplicationRecord, retrieveInterestResponseInterest.interestApplicationRecord) &&
        Objects.equals(this.interestTransaction, retrieveInterestResponseInterest.interestTransaction) &&
        Objects.equals(this.transactionDescription, retrieveInterestResponseInterest.transactionDescription) &&
        Objects.equals(this.transactionRateType, retrieveInterestResponseInterest.transactionRateType) &&
        Objects.equals(this.transactionInterestCharge, retrieveInterestResponseInterest.transactionInterestCharge) &&
        Objects.equals(this.interestAccrualAmount, retrieveInterestResponseInterest.interestAccrualAmount) &&
        Objects.equals(this.interestAccrualType, retrieveInterestResponseInterest.interestAccrualType) &&
        Objects.equals(this.interestAccrualCharge, retrieveInterestResponseInterest.interestAccrualCharge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interestRateType, interestRateApplicationSchedule, interestRateConfiguration, interestApplicationRecord, interestTransaction, transactionDescription, transactionRateType, transactionInterestCharge, interestAccrualAmount, interestAccrualType, interestAccrualCharge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveInterestResponseInterest {\n");
    
    sb.append("    interestRateType: ").append(toIndentedString(interestRateType)).append("\n");
    sb.append("    interestRateApplicationSchedule: ").append(toIndentedString(interestRateApplicationSchedule)).append("\n");
    sb.append("    interestRateConfiguration: ").append(toIndentedString(interestRateConfiguration)).append("\n");
    sb.append("    interestApplicationRecord: ").append(toIndentedString(interestApplicationRecord)).append("\n");
    sb.append("    interestTransaction: ").append(toIndentedString(interestTransaction)).append("\n");
    sb.append("    transactionDescription: ").append(toIndentedString(transactionDescription)).append("\n");
    sb.append("    transactionRateType: ").append(toIndentedString(transactionRateType)).append("\n");
    sb.append("    transactionInterestCharge: ").append(toIndentedString(transactionInterestCharge)).append("\n");
    sb.append("    interestAccrualAmount: ").append(toIndentedString(interestAccrualAmount)).append("\n");
    sb.append("    interestAccrualType: ").append(toIndentedString(interestAccrualType)).append("\n");
    sb.append("    interestAccrualCharge: ").append(toIndentedString(interestAccrualCharge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
