/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.kb.sample.savings.model;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;


import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Fulfill any scheduled and ad-hoc obligations under a service arrangement, most typically for a financial product or facility within Savings Account. 
 */
@Schema(description = "Fulfill any scheduled and ad-hoc obligations under a service arrangement, most typically for a financial product or facility within Savings Account. ")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class SavingsAccountFacility {
  @JsonProperty("ProductInstanceReference")
  private String productInstanceReference = null;

  @JsonProperty("SavingsAccountNumber")
  private String savingsAccountNumber = null;

  @JsonProperty("CustomerReference")
  private String customerReference = null;

  @JsonProperty("BankBranchLocationReference")
  private String bankBranchLocationReference = null;

  @JsonProperty("AccountType")
  private String accountType = null;

  @JsonProperty("AccountCurrency")
  private Currencycode accountCurrency = null;

  @JsonProperty("TaxReference")
  private String taxReference = null;

  @JsonProperty("EntitlementOptionDefinition")
  private String entitlementOptionDefinition = null;

  @JsonProperty("EntitlementOptionSetting")
  private String entitlementOptionSetting = null;

  @JsonProperty("RestrictionOptionDefinition")
  private String restrictionOptionDefinition = null;

  @JsonProperty("RestrictionOptionSetting")
  private String restrictionOptionSetting = null;

  @JsonProperty("Associations")
  private String associations = null;

  @JsonProperty("AssociationType")
  private String associationType = null;

  @JsonProperty("AssociationObligationEntitlement")
  private String associationObligationEntitlement = null;

  @JsonProperty("AssociationReference")
  private String associationReference = null;

  @JsonProperty("LinkedAccounts")
  private String linkedAccounts = null;

  @JsonProperty("LinkType")
  private String linkType = null;

  @JsonProperty("AccountDetails")
  private String accountDetails = null;

  @JsonProperty("PositionLimits")
  private String positionLimits = null;

  @JsonProperty("PositionLimitType")
  private String positionLimitType = null;

  @JsonProperty("PositionLimitSettings")
  private String positionLimitSettings = null;

  @JsonProperty("PositionLimitValue")
  private String positionLimitValue = null;

  @JsonProperty("DateType")
  private String dateType = null;

  @JsonProperty("Date")
  private String date = null;

  @JsonProperty("StatementsSchedule")
  private String statementsSchedule = null;

  @JsonProperty("StatementType")
  private String statementType = null;

  @JsonProperty("StatementTransactionType")
  private String statementTransactionType = null;

  @JsonProperty("StatementPeriod")
  private String statementPeriod = null;

  @JsonProperty("StatementReport")
  private String statementReport = null;

  public SavingsAccountFacility productInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
    return this;
  }

   /**
   * Reference to the savings account product instance
   * @return productInstanceReference
  **/
  @Schema(description = "Reference to the savings account product instance")
  public String getProductInstanceReference() {
    return productInstanceReference;
  }

  public void setProductInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
  }

  public SavingsAccountFacility savingsAccountNumber(String savingsAccountNumber) {
    this.savingsAccountNumber = savingsAccountNumber;
    return this;
  }

   /**
   * The associated account number in any suitable format (e.g. IBAN)
   * @return savingsAccountNumber
  **/
  @Schema(description = "The associated account number in any suitable format (e.g. IBAN)")
  public String getSavingsAccountNumber() {
    return savingsAccountNumber;
  }

  public void setSavingsAccountNumber(String savingsAccountNumber) {
    this.savingsAccountNumber = savingsAccountNumber;
  }

  public SavingsAccountFacility customerReference(String customerReference) {
    this.customerReference = customerReference;
    return this;
  }

   /**
   * Reference to the account primary party/owner
   * @return customerReference
  **/
  @Schema(description = "Reference to the account primary party/owner")
  public String getCustomerReference() {
    return customerReference;
  }

  public void setCustomerReference(String customerReference) {
    this.customerReference = customerReference;
  }

  public SavingsAccountFacility bankBranchLocationReference(String bankBranchLocationReference) {
    this.bankBranchLocationReference = bankBranchLocationReference;
    return this;
  }

   /**
   * Bank branch associated with the account for booking purposes
   * @return bankBranchLocationReference
  **/
  @Schema(description = "Bank branch associated with the account for booking purposes")
  public String getBankBranchLocationReference() {
    return bankBranchLocationReference;
  }

  public void setBankBranchLocationReference(String bankBranchLocationReference) {
    this.bankBranchLocationReference = bankBranchLocationReference;
  }

  public SavingsAccountFacility accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * The type of savings account (e.g. checking, student, small business)
   * @return accountType
  **/
  @Schema(description = "The type of savings account (e.g. checking, student, small business)")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public SavingsAccountFacility accountCurrency(Currencycode accountCurrency) {
    this.accountCurrency = accountCurrency;
    return this;
  }

   /**
   * Get accountCurrency
   * @return accountCurrency
  **/
  @Schema(description = "")
  public Currencycode getAccountCurrency() {
    return accountCurrency;
  }

  public void setAccountCurrency(Currencycode accountCurrency) {
    this.accountCurrency = accountCurrency;
  }

  public SavingsAccountFacility taxReference(String taxReference) {
    this.taxReference = taxReference;
    return this;
  }

   /**
   * Reference identifier linking the account to appropriate tax handling
   * @return taxReference
  **/
  @Schema(description = "Reference identifier linking the account to appropriate tax handling")
  public String getTaxReference() {
    return taxReference;
  }

  public void setTaxReference(String taxReference) {
    this.taxReference = taxReference;
  }

  public SavingsAccountFacility entitlementOptionDefinition(String entitlementOptionDefinition) {
    this.entitlementOptionDefinition = entitlementOptionDefinition;
    return this;
  }

   /**
   * The definition of an applicable entitlement option
   * @return entitlementOptionDefinition
  **/
  @Schema(description = "The definition of an applicable entitlement option")
  public String getEntitlementOptionDefinition() {
    return entitlementOptionDefinition;
  }

  public void setEntitlementOptionDefinition(String entitlementOptionDefinition) {
    this.entitlementOptionDefinition = entitlementOptionDefinition;
  }

  public SavingsAccountFacility entitlementOptionSetting(String entitlementOptionSetting) {
    this.entitlementOptionSetting = entitlementOptionSetting;
    return this;
  }

   /**
   * The setting for the entitlement option
   * @return entitlementOptionSetting
  **/
  @Schema(description = "The setting for the entitlement option")
  public String getEntitlementOptionSetting() {
    return entitlementOptionSetting;
  }

  public void setEntitlementOptionSetting(String entitlementOptionSetting) {
    this.entitlementOptionSetting = entitlementOptionSetting;
  }

  public SavingsAccountFacility restrictionOptionDefinition(String restrictionOptionDefinition) {
    this.restrictionOptionDefinition = restrictionOptionDefinition;
    return this;
  }

   /**
   * The definition of an applicable restriction option
   * @return restrictionOptionDefinition
  **/
  @Schema(description = "The definition of an applicable restriction option")
  public String getRestrictionOptionDefinition() {
    return restrictionOptionDefinition;
  }

  public void setRestrictionOptionDefinition(String restrictionOptionDefinition) {
    this.restrictionOptionDefinition = restrictionOptionDefinition;
  }

  public SavingsAccountFacility restrictionOptionSetting(String restrictionOptionSetting) {
    this.restrictionOptionSetting = restrictionOptionSetting;
    return this;
  }

   /**
   * The setting for the restriction option
   * @return restrictionOptionSetting
  **/
  @Schema(description = "The setting for the restriction option")
  public String getRestrictionOptionSetting() {
    return restrictionOptionSetting;
  }

  public void setRestrictionOptionSetting(String restrictionOptionSetting) {
    this.restrictionOptionSetting = restrictionOptionSetting;
  }

  public SavingsAccountFacility associations(String associations) {
    this.associations = associations;
    return this;
  }

   /**
   * Definition of the associations to the account
   * @return associations
  **/
  @Schema(description = "Definition of the associations to the account")
  public String getAssociations() {
    return associations;
  }

  public void setAssociations(String associations) {
    this.associations = associations;
  }

  public SavingsAccountFacility associationType(String associationType) {
    this.associationType = associationType;
    return this;
  }

   /**
   * The type of association (e.g. guarantor, co-signer)
   * @return associationType
  **/
  @Schema(description = "The type of association (e.g. guarantor, co-signer)")
  public String getAssociationType() {
    return associationType;
  }

  public void setAssociationType(String associationType) {
    this.associationType = associationType;
  }

  public SavingsAccountFacility associationObligationEntitlement(String associationObligationEntitlement) {
    this.associationObligationEntitlement = associationObligationEntitlement;
    return this;
  }

   /**
   * Description of the role, obligations or entitlements of the associated party
   * @return associationObligationEntitlement
  **/
  @Schema(description = "Description of the role, obligations or entitlements of the associated party")
  public String getAssociationObligationEntitlement() {
    return associationObligationEntitlement;
  }

  public void setAssociationObligationEntitlement(String associationObligationEntitlement) {
    this.associationObligationEntitlement = associationObligationEntitlement;
  }

  public SavingsAccountFacility associationReference(String associationReference) {
    this.associationReference = associationReference;
    return this;
  }

   /**
   * Reference to the associated party
   * @return associationReference
  **/
  @Schema(description = "Reference to the associated party")
  public String getAssociationReference() {
    return associationReference;
  }

  public void setAssociationReference(String associationReference) {
    this.associationReference = associationReference;
  }

  public SavingsAccountFacility linkedAccounts(String linkedAccounts) {
    this.linkedAccounts = linkedAccounts;
    return this;
  }

   /**
   * Definition of the associations to the account
   * @return linkedAccounts
  **/
  @Schema(description = "Definition of the associations to the account")
  public String getLinkedAccounts() {
    return linkedAccounts;
  }

  public void setLinkedAccounts(String linkedAccounts) {
    this.linkedAccounts = linkedAccounts;
  }

  public SavingsAccountFacility linkType(String linkType) {
    this.linkType = linkType;
    return this;
  }

   /**
   * The type and purpose for the link
   * @return linkType
  **/
  @Schema(description = "The type and purpose for the link")
  public String getLinkType() {
    return linkType;
  }

  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }

  public SavingsAccountFacility accountDetails(String accountDetails) {
    this.accountDetails = accountDetails;
    return this;
  }

   /**
   * Details of the linked account
   * @return accountDetails
  **/
  @Schema(description = "Details of the linked account")
  public String getAccountDetails() {
    return accountDetails;
  }

  public void setAccountDetails(String accountDetails) {
    this.accountDetails = accountDetails;
  }

  public SavingsAccountFacility positionLimits(String positionLimits) {
    this.positionLimits = positionLimits;
    return this;
  }

   /**
   * Position limits that are maintained by the account
   * @return positionLimits
  **/
  @Schema(description = "Position limits that are maintained by the account")
  public String getPositionLimits() {
    return positionLimits;
  }

  public void setPositionLimits(String positionLimits) {
    this.positionLimits = positionLimits;
  }

  public SavingsAccountFacility positionLimitType(String positionLimitType) {
    this.positionLimitType = positionLimitType;
    return this;
  }

   /**
   * The type of position maintained for the account (e.g. transaction credit/debit, netting, position)
   * @return positionLimitType
  **/
  @Schema(description = "The type of position maintained for the account (e.g. transaction credit/debit, netting, position)")
  public String getPositionLimitType() {
    return positionLimitType;
  }

  public void setPositionLimitType(String positionLimitType) {
    this.positionLimitType = positionLimitType;
  }

  public SavingsAccountFacility positionLimitSettings(String positionLimitSettings) {
    this.positionLimitSettings = positionLimitSettings;
    return this;
  }

   /**
   * The position definition, associated limit settings and rules
   * @return positionLimitSettings
  **/
  @Schema(description = "The position definition, associated limit settings and rules")
  public String getPositionLimitSettings() {
    return positionLimitSettings;
  }

  public void setPositionLimitSettings(String positionLimitSettings) {
    this.positionLimitSettings = positionLimitSettings;
  }

  public SavingsAccountFacility positionLimitValue(String positionLimitValue) {
    this.positionLimitValue = positionLimitValue;
    return this;
  }

   /**
   * The savings calculated position
   * @return positionLimitValue
  **/
  @Schema(description = "The savings calculated position")
  public String getPositionLimitValue() {
    return positionLimitValue;
  }

  public void setPositionLimitValue(String positionLimitValue) {
    this.positionLimitValue = positionLimitValue;
  }

  public SavingsAccountFacility dateType(String dateType) {
    this.dateType = dateType;
    return this;
  }

   /**
   * Key dates associated with the account (e.g. opening date, closing date)
   * @return dateType
  **/
  @Schema(description = "Key dates associated with the account (e.g. opening date, closing date)")
  public String getDateType() {
    return dateType;
  }

  public void setDateType(String dateType) {
    this.dateType = dateType;
  }

  public SavingsAccountFacility date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Value of the date type
   * @return date
  **/
  @Schema(description = "Value of the date type")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public SavingsAccountFacility statementsSchedule(String statementsSchedule) {
    this.statementsSchedule = statementsSchedule;
    return this;
  }

   /**
   * The schedule for generating product statements to schedule
   * @return statementsSchedule
  **/
  @Schema(description = "The schedule for generating product statements to schedule")
  public String getStatementsSchedule() {
    return statementsSchedule;
  }

  public void setStatementsSchedule(String statementsSchedule) {
    this.statementsSchedule = statementsSchedule;
  }

  public SavingsAccountFacility statementType(String statementType) {
    this.statementType = statementType;
    return this;
  }

   /**
   * The types of scheduled statement (e.g. balance/mini-statement/annual)
   * @return statementType
  **/
  @Schema(description = "The types of scheduled statement (e.g. balance/mini-statement/annual)")
  public String getStatementType() {
    return statementType;
  }

  public void setStatementType(String statementType) {
    this.statementType = statementType;
  }

  public SavingsAccountFacility statementTransactionType(String statementTransactionType) {
    this.statementTransactionType = statementTransactionType;
    return this;
  }

   /**
   * The types of transactions and transaction details to be included
   * @return statementTransactionType
  **/
  @Schema(description = "The types of transactions and transaction details to be included")
  public String getStatementTransactionType() {
    return statementTransactionType;
  }

  public void setStatementTransactionType(String statementTransactionType) {
    this.statementTransactionType = statementTransactionType;
  }

  public SavingsAccountFacility statementPeriod(String statementPeriod) {
    this.statementPeriod = statementPeriod;
    return this;
  }

   /**
   * The reporting period covered by the statement
   * @return statementPeriod
  **/
  @Schema(description = "The reporting period covered by the statement")
  public String getStatementPeriod() {
    return statementPeriod;
  }

  public void setStatementPeriod(String statementPeriod) {
    this.statementPeriod = statementPeriod;
  }

  public SavingsAccountFacility statementReport(String statementReport) {
    this.statementReport = statementReport;
    return this;
  }

   /**
   * The statement content
   * @return statementReport
  **/
  @Schema(description = "The statement content")
  public String getStatementReport() {
    return statementReport;
  }

  public void setStatementReport(String statementReport) {
    this.statementReport = statementReport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SavingsAccountFacility savingsAccountFacility = (SavingsAccountFacility) o;
    return Objects.equals(this.productInstanceReference, savingsAccountFacility.productInstanceReference) &&
        Objects.equals(this.savingsAccountNumber, savingsAccountFacility.savingsAccountNumber) &&
        Objects.equals(this.customerReference, savingsAccountFacility.customerReference) &&
        Objects.equals(this.bankBranchLocationReference, savingsAccountFacility.bankBranchLocationReference) &&
        Objects.equals(this.accountType, savingsAccountFacility.accountType) &&
        Objects.equals(this.accountCurrency, savingsAccountFacility.accountCurrency) &&
        Objects.equals(this.taxReference, savingsAccountFacility.taxReference) &&
        Objects.equals(this.entitlementOptionDefinition, savingsAccountFacility.entitlementOptionDefinition) &&
        Objects.equals(this.entitlementOptionSetting, savingsAccountFacility.entitlementOptionSetting) &&
        Objects.equals(this.restrictionOptionDefinition, savingsAccountFacility.restrictionOptionDefinition) &&
        Objects.equals(this.restrictionOptionSetting, savingsAccountFacility.restrictionOptionSetting) &&
        Objects.equals(this.associations, savingsAccountFacility.associations) &&
        Objects.equals(this.associationType, savingsAccountFacility.associationType) &&
        Objects.equals(this.associationObligationEntitlement, savingsAccountFacility.associationObligationEntitlement) &&
        Objects.equals(this.associationReference, savingsAccountFacility.associationReference) &&
        Objects.equals(this.linkedAccounts, savingsAccountFacility.linkedAccounts) &&
        Objects.equals(this.linkType, savingsAccountFacility.linkType) &&
        Objects.equals(this.accountDetails, savingsAccountFacility.accountDetails) &&
        Objects.equals(this.positionLimits, savingsAccountFacility.positionLimits) &&
        Objects.equals(this.positionLimitType, savingsAccountFacility.positionLimitType) &&
        Objects.equals(this.positionLimitSettings, savingsAccountFacility.positionLimitSettings) &&
        Objects.equals(this.positionLimitValue, savingsAccountFacility.positionLimitValue) &&
        Objects.equals(this.dateType, savingsAccountFacility.dateType) &&
        Objects.equals(this.date, savingsAccountFacility.date) &&
        Objects.equals(this.statementsSchedule, savingsAccountFacility.statementsSchedule) &&
        Objects.equals(this.statementType, savingsAccountFacility.statementType) &&
        Objects.equals(this.statementTransactionType, savingsAccountFacility.statementTransactionType) &&
        Objects.equals(this.statementPeriod, savingsAccountFacility.statementPeriod) &&
        Objects.equals(this.statementReport, savingsAccountFacility.statementReport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productInstanceReference, savingsAccountNumber, customerReference, bankBranchLocationReference, accountType, accountCurrency, taxReference, entitlementOptionDefinition, entitlementOptionSetting, restrictionOptionDefinition, restrictionOptionSetting, associations, associationType, associationObligationEntitlement, associationReference, linkedAccounts, linkType, accountDetails, positionLimits, positionLimitType, positionLimitSettings, positionLimitValue, dateType, date, statementsSchedule, statementType, statementTransactionType, statementPeriod, statementReport);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SavingsAccountFacility {\n");
    
    sb.append("    productInstanceReference: ").append(toIndentedString(productInstanceReference)).append("\n");
    sb.append("    savingsAccountNumber: ").append(toIndentedString(savingsAccountNumber)).append("\n");
    sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
    sb.append("    bankBranchLocationReference: ").append(toIndentedString(bankBranchLocationReference)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    accountCurrency: ").append(toIndentedString(accountCurrency)).append("\n");
    sb.append("    taxReference: ").append(toIndentedString(taxReference)).append("\n");
    sb.append("    entitlementOptionDefinition: ").append(toIndentedString(entitlementOptionDefinition)).append("\n");
    sb.append("    entitlementOptionSetting: ").append(toIndentedString(entitlementOptionSetting)).append("\n");
    sb.append("    restrictionOptionDefinition: ").append(toIndentedString(restrictionOptionDefinition)).append("\n");
    sb.append("    restrictionOptionSetting: ").append(toIndentedString(restrictionOptionSetting)).append("\n");
    sb.append("    associations: ").append(toIndentedString(associations)).append("\n");
    sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
    sb.append("    associationObligationEntitlement: ").append(toIndentedString(associationObligationEntitlement)).append("\n");
    sb.append("    associationReference: ").append(toIndentedString(associationReference)).append("\n");
    sb.append("    linkedAccounts: ").append(toIndentedString(linkedAccounts)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    accountDetails: ").append(toIndentedString(accountDetails)).append("\n");
    sb.append("    positionLimits: ").append(toIndentedString(positionLimits)).append("\n");
    sb.append("    positionLimitType: ").append(toIndentedString(positionLimitType)).append("\n");
    sb.append("    positionLimitSettings: ").append(toIndentedString(positionLimitSettings)).append("\n");
    sb.append("    positionLimitValue: ").append(toIndentedString(positionLimitValue)).append("\n");
    sb.append("    dateType: ").append(toIndentedString(dateType)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    statementsSchedule: ").append(toIndentedString(statementsSchedule)).append("\n");
    sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
    sb.append("    statementTransactionType: ").append(toIndentedString(statementTransactionType)).append("\n");
    sb.append("    statementPeriod: ").append(toIndentedString(statementPeriod)).append("\n");
    sb.append("    statementReport: ").append(toIndentedString(statementReport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
