/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hs.sample.k.apiserver.model;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.Objects;
import java.util.Arrays;





import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
//import org.threeten.bp.LocalDate;
/**
 * ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals {
  @JsonProperty("DepositTransactionDate")
  private LocalDate depositTransactionDate = null;

  @JsonProperty("WithdrawalTransactionDate")
  private LocalDate withdrawalTransactionDate = null;

  public ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals depositTransactionDate(LocalDate depositTransactionDate) {
    this.depositTransactionDate = depositTransactionDate;
    return this;
  }

   /**
   * Get depositTransactionDate
   * @return depositTransactionDate
  **/
  @Schema(description = "")
  public LocalDate getDepositTransactionDate() {
    return depositTransactionDate;
  }

  public void setDepositTransactionDate(LocalDate depositTransactionDate) {
    this.depositTransactionDate = depositTransactionDate;
  }

  public ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals withdrawalTransactionDate(LocalDate withdrawalTransactionDate) {
    this.withdrawalTransactionDate = withdrawalTransactionDate;
    return this;
  }

   /**
   * Get withdrawalTransactionDate
   * @return withdrawalTransactionDate
  **/
  @Schema(description = "")
  public LocalDate getWithdrawalTransactionDate() {
    return withdrawalTransactionDate;
  }

  public void setWithdrawalTransactionDate(LocalDate withdrawalTransactionDate) {
    this.withdrawalTransactionDate = withdrawalTransactionDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals executeDepositsandWithdrawalsResponseDepositsandWithdrawals = (ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals) o;
    return Objects.equals(this.depositTransactionDate, executeDepositsandWithdrawalsResponseDepositsandWithdrawals.depositTransactionDate) &&
        Objects.equals(this.withdrawalTransactionDate, executeDepositsandWithdrawalsResponseDepositsandWithdrawals.withdrawalTransactionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depositTransactionDate, withdrawalTransactionDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteDepositsandWithdrawalsResponseDepositsandWithdrawals {\n");
    
    sb.append("    depositTransactionDate: ").append(toIndentedString(depositTransactionDate)).append("\n");
    sb.append("    withdrawalTransactionDate: ").append(toIndentedString(withdrawalTransactionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
