/*
 * Savings Account
 * This service domain orchestrates a consumer savings account. The typical range of services and fees covers payments from and scheduled and ad-hoc deposits to the account, standing orders, sweeps, and liens.
 *
 * OpenAPI spec version: 11.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hs.sample.k.apiserver.model;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;
import java.util.Arrays;





import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RequestIssuedDeviceRequestIssuedDevice
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-20T14:18:15.269223656Z[GMT]")

public class RequestIssuedDeviceRequestIssuedDevice {
  @JsonProperty("IssuedDeviceType")
  private String issuedDeviceType = null;

  @JsonProperty("IssuedDeviceOptionSetting")
  private String issuedDeviceOptionSetting = null;

  @JsonProperty("IssuedDeviceProperty")
  private String issuedDeviceProperty = null;

  @JsonProperty("IssuedDevicePropertyValue")
  private String issuedDevicePropertyValue = null;

  @JsonProperty("IssuedDeviceStatus")
  private String issuedDeviceStatus = null;

  public RequestIssuedDeviceRequestIssuedDevice issuedDeviceType(String issuedDeviceType) {
    this.issuedDeviceType = issuedDeviceType;
    return this;
  }

   /**
   *  
   * @return issuedDeviceType
  **/
  @Schema(description = " ")
  public String getIssuedDeviceType() {
    return issuedDeviceType;
  }

  public void setIssuedDeviceType(String issuedDeviceType) {
    this.issuedDeviceType = issuedDeviceType;
  }

  public RequestIssuedDeviceRequestIssuedDevice issuedDeviceOptionSetting(String issuedDeviceOptionSetting) {
    this.issuedDeviceOptionSetting = issuedDeviceOptionSetting;
    return this;
  }

   /**
   *  
   * @return issuedDeviceOptionSetting
  **/
  @Schema(description = " ")
  public String getIssuedDeviceOptionSetting() {
    return issuedDeviceOptionSetting;
  }

  public void setIssuedDeviceOptionSetting(String issuedDeviceOptionSetting) {
    this.issuedDeviceOptionSetting = issuedDeviceOptionSetting;
  }

  public RequestIssuedDeviceRequestIssuedDevice issuedDeviceProperty(String issuedDeviceProperty) {
    this.issuedDeviceProperty = issuedDeviceProperty;
    return this;
  }

   /**
   *  
   * @return issuedDeviceProperty
  **/
  @Schema(description = " ")
  public String getIssuedDeviceProperty() {
    return issuedDeviceProperty;
  }

  public void setIssuedDeviceProperty(String issuedDeviceProperty) {
    this.issuedDeviceProperty = issuedDeviceProperty;
  }

  public RequestIssuedDeviceRequestIssuedDevice issuedDevicePropertyValue(String issuedDevicePropertyValue) {
    this.issuedDevicePropertyValue = issuedDevicePropertyValue;
    return this;
  }

   /**
   *  
   * @return issuedDevicePropertyValue
  **/
  @Schema(description = " ")
  public String getIssuedDevicePropertyValue() {
    return issuedDevicePropertyValue;
  }

  public void setIssuedDevicePropertyValue(String issuedDevicePropertyValue) {
    this.issuedDevicePropertyValue = issuedDevicePropertyValue;
  }

  public RequestIssuedDeviceRequestIssuedDevice issuedDeviceStatus(String issuedDeviceStatus) {
    this.issuedDeviceStatus = issuedDeviceStatus;
    return this;
  }

   /**
   *  
   * @return issuedDeviceStatus
  **/
  @Schema(description = " ")
  public String getIssuedDeviceStatus() {
    return issuedDeviceStatus;
  }

  public void setIssuedDeviceStatus(String issuedDeviceStatus) {
    this.issuedDeviceStatus = issuedDeviceStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestIssuedDeviceRequestIssuedDevice requestIssuedDeviceRequestIssuedDevice = (RequestIssuedDeviceRequestIssuedDevice) o;
    return Objects.equals(this.issuedDeviceType, requestIssuedDeviceRequestIssuedDevice.issuedDeviceType) &&
        Objects.equals(this.issuedDeviceOptionSetting, requestIssuedDeviceRequestIssuedDevice.issuedDeviceOptionSetting) &&
        Objects.equals(this.issuedDeviceProperty, requestIssuedDeviceRequestIssuedDevice.issuedDeviceProperty) &&
        Objects.equals(this.issuedDevicePropertyValue, requestIssuedDeviceRequestIssuedDevice.issuedDevicePropertyValue) &&
        Objects.equals(this.issuedDeviceStatus, requestIssuedDeviceRequestIssuedDevice.issuedDeviceStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedDeviceType, issuedDeviceOptionSetting, issuedDeviceProperty, issuedDevicePropertyValue, issuedDeviceStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestIssuedDeviceRequestIssuedDevice {\n");
    
    sb.append("    issuedDeviceType: ").append(toIndentedString(issuedDeviceType)).append("\n");
    sb.append("    issuedDeviceOptionSetting: ").append(toIndentedString(issuedDeviceOptionSetting)).append("\n");
    sb.append("    issuedDeviceProperty: ").append(toIndentedString(issuedDeviceProperty)).append("\n");
    sb.append("    issuedDevicePropertyValue: ").append(toIndentedString(issuedDevicePropertyValue)).append("\n");
    sb.append("    issuedDeviceStatus: ").append(toIndentedString(issuedDeviceStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
