
server:
  port: 8080
  error:
    include-stacktrace: never


spring.output.ansi.enabled: always


error:
  printStackTrace: true

management:
  endpoints:
    web.base-path: /management # actuator 기본 경로 변경 (보안)
    web.exposure.include: "health,info,env,metrics"
  server:
    port: 8082 # http://localhost:8082/actuator (port 8080 -> 8082)
  endpoint:
    health:
      show-details: ALWAYS # http://localhost:8082/actuator/health 에서 "up" 상태코드 외 다른 상세정보 보여줌
    env:
      show-values: ALWAYS # http://localhost:8082/actuator/env 에서 값이 보이게 하는 설정
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true # 아래 info key 값의 데이터를 표시
info:
  my-app:
    any-value: someValue
    group-id: "@project.groupId@" # maven 의 properties 가져오는 문법


integration:
  account:
    url: http://localhost:19000
    token:
  product:
    url: http://localhost:9090
    token: