server:
  port: 28081

otel:
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: cart
        namespace: shop
  instrumentation:
    jdbc:
      enabled: false
    logback-appender:
      enabled: false
    spring-web:
      enabled: false
    spring-webmvc:
      enabled: false
    spring-webflux:
      enabled: false
    kafka:
      enabled: false
    mongo:
      enabled: false
    micrometer:
      enabled: false
    r2dbc:
      enabled: false
#  Logback	otel.instrumentation.logback-appender.enabled	true
#  Spring Web	otel.instrumentation.spring-web.enabled	true
#  Spring Web MVC	otel.instrumentation.spring-webmvc.enabled	true
#  Spring WebFlux	otel.instrumentation.spring-webflux.enabled	true
#  Kafka	otel.instrumentation.kafka.enabled	true
#  MongoDB	otel.instrumentation.mongo.enabled	true
#  Micrometer	otel.instrumentation.micrometer.enabled	false
#  R2DBC (reactive JDBC)	otel.instrumentation.r2dbc.enabled	true
