drop table if exists product_directory cascade ;
create table product_directory (
    id bigint generated by default as identity,
    product_instance_reference VARCHAR(255) COMMENT '상품 인스턴스 참조번호',
    product_name VARCHAR(255) COMMENT '상품명',
    product_name_eng VARCHAR(255) COMMENT '상품명 (영어)',
    product_status_code VARCHAR(255) COMMENT '상품 상태코드',
    sales_end_ymd VARCHAR(255) COMMENT '상품 판매 종료일',
    sales_start_ymd VARCHAR(255) COMMENT '상품 판매 시작일',
    primary key (id)
);